apiVersion: batch/v1
kind: Job
metadata:
  name: demo-job
spec:
  template:
    spec:
      containers:
      - name: demo-container
        image: gcr.io/k8s-k3s/demo:v1.0.0
        command:
        - /bin/sh
        - -c
        - echo "Hello from the Kubernetes Job"
      restartPolicy: OnFailure
