apiVersion: v1
kind: Pod
metadata:
  name: demo-secret
spec:
  containers:
  - name: demo
    image: busybox
    volumeMounts:
    - name: secret
      mountPath: /etc/foo
      readOnly: true
  volumes:
  - name: secret
    secret:
      secretName: simple-secret