apiVersion: batch/v1
kind: CronJob
metadata:
  name: demo-cronjob
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: demo-container
            image: gcr.io/k8s-k3s/demo:v1.0.0
            command: ["echo",  "Hello world"]
          restartPolicy: OnFailure
